todoproject/todoapp/urls.py
from . import views
from django.urls import path
app_name = 'todoapp'
urlpatterns = [
    path('', views.home, name='home'),
    path('delete/<int:taskid>/', views.delete, name='delete'),
    path('update/<int:id>/', views.update, name='update'),
    path('cbvhome/', views.TaskListView.as_view(), name='cbvhome'),
    path('cbvdetails/<int:pk>/', views.TaskDetailView.as_view(), name='cbvdetails'),
    path('cbvupdate/<int:pk>/', views.TaskUpdateView.as_view(), name='cbvupdate'),
    path('cbvdelete/<int:pk>/', views.TaskDeleteView.as_view(), name='cbvdelete')
]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todoapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=150)
    priority = models.IntegerField()
    date = models.DateField()

todoproject/todoapp/forms.py
from .models import Task
from django import forms


class TodoForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'priority', 'date']

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView

from .forms import TodoForm
from .models import Task


# Create your views here.

class TaskListView(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'


class TaskDetailView(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'


class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'update.html'
    context_object_name = 'task'
    fields = ('name', 'date', 'priority')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetails', kwargs={'pk': self.object.pk})


class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')




def home(request):
    task1 = Task.objects.all()
    context = {'task1': task1}
    if request.method == 'POST':
        name = request.POST.get('task', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task = Task(name=name, priority=priority, date=date)
        task.save()

    return render(request, 'home.html', context)


def delete(request, taskid):
    if request.method == 'POST':
        task = Task.objects.get(id=taskid)
        task.delete()
        return redirect('/')
    return render(request, 'delete.html')


def update(request, id):
    task = Task.objects.get(id=id)
    f = TodoForm(request.POST or None, instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')
    return render(request, 'edit.html', {'f': f, 'task': task})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
<h4>did you complete the Task?</h4>
<button type="submit">Yes</button>
</form>
{% endblock %}

todoproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="card shadow">
               <div class="card-body">
                   <h5 class="card-title">{{task.name}}</h5>
                   <p><b>{{task.priority}}</b></p>
                   <p><b>{{task.date}}</b></p>
                   <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">Done</a>
                   <a class="btn btn-success" href="{% url 'todoapp:update' task.id %}">Update</a>
               </div>
           </div>
           <br>
{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{f.as_p}}
    <button type="submit">Submit</button>
</form>
{% endblock%}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h2>ToDo Tasks</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form class="p-3 shadow" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
                <div class="form-group">
    <input type="text" name="task" class="form-control" placeholder="Enter the Task">
                </div>
                <br>
                <div class="form-group">
    <input type="text" class="form-control" name="priority" placeholder="Enter Priority">
                </div>
                <br>
                <div class="form-group">
    <input type="date" class="form-control" name="date" placeholder="Enter the date">
                </div>
                <br>
    <input type="submit" class="btn btn-success" value="Submit">
            </form>
        </div>
       <div class="col-md-6">
           <h5>Tasks to be completed</h5>
           {% for i in task1 %}
           <div class="card shadow">
               <div class="card-body">
                   <h5 class="card-title">{{i.name}}</h5>
                   <p><b>{{i.priority}}</b></p>
                   <p><b>{{i.date}}</b></p>
                   <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">Done</a>
                   <a class="btn btn-success" href="{% url 'todoapp:update' i.id %}">Update</a>
               </div>
           </div>
           <br>
           {% endfor %}
       </div>
    </div>
</div>
{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
<div class="card">
    <div class="card-hearder">
        <div class="card-title">
            Task Update
        </div>
        <form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Submit</button>
</form>
    </div>
</div>
{% endblock %}